apiVersion: connectors.aiops.ibm.com/v1beta1
kind: BundleManifest
metadata:
  name: smax
spec:
  prereqs:
    repo: https://github.com/styblope/cp4aiops-smax-integration-public
    branch: main
    components:
      - name: deployment
        path: /bundle-artifacts/prereqs
        type: kustomize
  instanced:
    repo: https://github.com/styblope/cp4aiops-smax-integration-public
    branch: main
    components:
      - name: connector
        path: /bundle-artifacts/connector
        type: kustomize
