apiVersion: connectors.aiops.ibm.com/v1beta1
kind: ConnectorSchema
metadata:
  name: smax
  labels:
    aiops-connector-category-ticketing: "true" # For integration to appear under Ticketing section in policy. Use notifications-connector: "true" instead for it to be under Notifications. 
spec:
  categories:
    - tickets
    - events
  ceType: com.ibm.aiops.connectors.configuration
  components:
    - apiType: AsyncAPI
      name: connector
  documentation: >- # change the documentation reference
    https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/4.10.1?topic=integrations-outgoing
  permissions:
    channels:
      - name: cp4waiops-cartridge.lifecycle.input.events # To create alerts
        operations:
          - write
      - name: cp4waiops-cartridge.itsmincidentresponse # To save the outbound system ticket number to the incident.
        operations:
          - write
      - name: cp4waiops-cartridge.lifecycle.input.connector-responses # To send back responses after creating tickets. 
        operations:
          - write
      - name: cp4waiops-cartridge.lifecycle.output.connector-requests # To listen to the incidents create/update/close events.
        operations:
          - read
  encryptedFields:
    - /password          
  schema:
    allOf:
      - required:
          - url
          - token
          - username
          - password
    properties:
      password:
        format: secret
        type: string
      types: # Don't change this as this is required and might have an impact
        type: string
      url:
        type: string
      username:
        type: string
      issueSamplingRate:
        type: integer
      datasource_type:
        description: List of categories
        items:
          type: string
        type: array
      historical_config:
        additionalProperties: false
        properties:
          collectionMode:
            default: historical
            enum:
              - historical
            type: string
          end_date:
            format: date-time
            type: string
          start_date:
            format: date-time
            type: string
        required:
          - collectionMode
          - start_date
          - end_date
        type: object  
      mappings:
        description: The incident creation mappings
        type: string
    type: object
  uiSchema:
    type: smax
    displayName: "SMAX Integration"
    iconFileType: png 
    iconFileSize: 96
    categories: 
      - "{{connector.common.category.notifications}}"
    url: https://ibm.biz/int-smax
    apiAdaptor: grpc
    datasourceType: tickets
    sidePanelTitle: "Configuring SMAX integration"
    # sidePanelDescription: "{{connector.servicenow.sidepanel.description}}"
    sidePanelDescription: |
      The integration publishes incidents from Cloud Pak for AIOps to SMAX (OpenText Service Management) and keeps their lifecycle and related data synchronized. The SMAX integration also collects both historical and real-time data on change requests, incidents, and problems. This information can then be used to calculate change risk scores.
    sidePanelInfoHeader: "{{sidePanel.information.header}}"
    sidePanelInfo:
      - "{{common.egress_warning}}"
      # - "{{sidePanel.information.servicenow.1}}"
      # - "{{sidePanel.information.servicenow.2}}"
      - "SMAX service URL"
      - "Tenant ID"
      - "User ID and password credentials"
    hasOptionalConfig: true
    sidePanelOptionalConfigHeader: "{{sidePanel.optional.config.header}}"
    sidePanelOptionalConfigList:
      - "{{sidePanel.optional.config.fieldMappingSearch}}"
    hasOptionalText: false
    hasAIModelType: true
    isObserver: false
    deploymentType: ["local", "remote"]
    AIModelTypeList:
      - "{{sidePanel.AIModelTypes.changeRisk}}" # Remove if change risk is not used 
      - "{{sidePanel.AIModelTypes.similarIncidents}}"  # Remove if similar tickets is not used
    formSteps:
      - step:
          id: addConnection
          name: "{{formSteps.addConnection}}"
      - step:
          id: fieldMapping
          name: "{{formSteps.fieldMapping}}"
          isOptional: true
      - step:
          id: collectTickets
          name: "{{formSteps.collectTickets}}"
          isOptional: true
    form:
      - id: type
        element: input
        type: hiddenText  
        defaultValue: ["tickets"]
        apiMapping: connection_config.datasource_type
        formStep: addConnection
      - id: name
        element: input
        type: text
        label: "{{connector.common.form.uniqueID.label}}"
        placeholder: "{{connector.common.form.ops_integration_name.placeholder}}"
        apiMapping: connection_config.display_name
        formStep: addConnection
        isRequired: true
        maxCharLength: 50
        isDisabledOnUpdate: true
        isAlphanumeric: true
      - id: description
        element: input
        type: textarea
        label: "{{connector.common.form.description.label}}"
        placeholder: "{{connector.common.form.description.placeholder}}"
        apiMapping: connection_config.description
        formStep: addConnection
        maxCharLength: 600
      - id: url
        element: input
        type: text
        label: "SMAX Base URL"
        placeholder: "e.g. https://newsmax.combis.hr"
        helperText: "{{common.egress_warning}}"
        apiMapping: connection_config.url
        formStep: addConnection
        isRequired: true
        isURL : true
      - id: tenant
        element: input
        type: text
        label: "Tenant ID"
        placeholder: "Enter the SMAX tenant ID"
        apiMapping: connection_config.tenant
        formStep: addConnection
        isRequired: true
      - id: username
        element: input
        type: text
        label: "{{connector.servicenow.form.user_id.label}}"
        placeholder: "{{connector.common.form.username.placeholder}}"
        apiMapping: connection_config.username
        formStep: addConnection
        isRequired: true
      - id: password
        element: input
        type: password
        label: "{{connector.common.form.password.label}}"
        placeholder: "{{connector.common.form.password.placeholder}}"
        apiMapping: connection_config.password
        formStep: addConnection
        isRequired: true
      - id: orchestration
        element: input
        type: radio
        label: "{{connector.common.form.orchestration.label}}"
        items: 
          - "{{common.filtering.local}}"
          - "{{common.filtering.remote}}"
        itemKeys: ["local", "microedge"]
        apiMapping: connection_config.deploymentType
        formStep: addConnection
        form:
          - id: local
          - id: microedge
            rows:
              - id: technology_notification
                element: input
                type: notification
                kind: info
                hideCloseButton: true
                title: "{{common.note}}"
                subtitle: "{{connection.appdynamics.deployment.notification}}"
      - id: connection_test
        element: input
        type: test
        label: "{{connector.common.form.connection_test.label}}"
        helperText: "{{connector.common.form.connection_test.helperText}}"
        formStep: addConnection
      - id: data_flow
        element: input
        type: toggle
        defaultToggled: false
        label: "{{connector.common.form.data_flow.label}}"
        labelOff: "{{common.Off}}"
        labelOn: "{{common.On}}"
        # headerLabel: "{{connector.common.form.ticketCollection.headerLabel}}"
        headerLabel: |
          First, specify whether you want to use live or historical ticket data when training the Change risk and Similar tickets algorithms. When using live data, you can also specify whether change risk assessments are performed, and define how alert and incident data is synchronized from SMAX to Cloud Pak for AIOps (Incident data is continuously synchronized from Cloud Pak for AIOps to SMAX). You can also enable and disable collection of all data from SMAX. Additional setup may be required before using this integration.
        apiMapping: connection_config.data_flow
        formStep: collectTickets
      - id: dynamic_schedule_form
        element: form
        label: "{{common.mode}}"
        items: 
          - "{{connection_form.dynamic_item.live.tickets}}"
          - "{{connection_form.dynamic_item.historical.tickets}}"
        itemKeys: ["live", "historical"]
        apiMapping: connection_config.collectionMode
        formStep: collectTickets
        form:
          - id: live
            rows:
              - id: issueSamplingRate
                element: input
                type: number
                # label: "{{connector.github.form.incident_sampling_rate.label}}"
                label: "SMAX issue sampling rate (1-60 minutes)"
                min: 1
                max: 60
                step: 1
                defaultValue: 1
                # helperText: "{{connector.github.form.incident_sampling_rate.helperText}}"
                helperText: "The frequency at which data is sampled for SMAX issues (in minutes). The default value is 1."
                apiMapping: connection_config.issueSamplingRate
                formStep: collectTickets
                isRequired: true
          - id: historical
            rows:
              - id: start
                element: input
                type: date
                label: "{{connector.common.form.start_date.label}}"
                placeholder: "{{connector.common.form.start_date.placeholder}}"
                apiMapping: connection_config.start
              - id: end
                element: input
                type: date
                label: "{{connector.common.form.end_date.label}}"
                placeholder: "{{connector.common.form.end_date.placeholder}}"
                apiMapping: connection_config.end
      - id: mappings
        element: input
        type: emailJsonata
        # headerLabel: "{{connector.github.form.mappings.message}}"
        headerLabel: |
          Here, you can customize the mapping of incident details to the SMAX data record. You can use the default issue template as-is, or customize it to include different information.
        headerLabelLink: https://ibm.biz/int-tickettemplate
        # label:  "{{connector.github.form.mappings.label}}"
        label: "Incident created SMAX issue record template"
        isRequired: true
        apiMapping: connection_config.mappings
        formStep: fieldMapping
        defaultValue: |
          ({
            "entity_type": "Request",
              "properties": {
                "Company_c": "10497",
                "Contract_c": "10501",
                "PublicScope": "Private",
                "RegisteredForActualService": "10515",
                "RequestType": "SupportRequest",
                "DisplayLabel": $string(incident.title),
                "Description": $join(["Incident Id:", $string(incident.id),
                       "\nAIOPS Incident Overview URL: https://", $string(URL_PREFIX), "/aiops/default/resolution-hub/incidents/all/", $string(incident.id), "/overview",
                       "\nStatus: ", $string(incident.state),
                       "\nDescription: ", $string(incident.description)]),
                "SbdNbd_c": false,
                "Priority": "LowPriority",
                "UserReferenceNumber_c": "IBM0001",
                "Priority_c": "LowPriority",
                "Integration_c": "AIOps_c",
                "RequestedForPerson":"15377",
                "RequestedByPerson":"15377",
                "ServiceDeskGroup":"10401",
                "PhaseId": "Log",
                "CreationSource": "CreationSourceOther",
                "FirstLine": true,
                "IsDeleted": false
              }
          })




