apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml
  # - topics.yaml

configurations:
  - custom-images.yaml

images:
  - name: ticket-template
    newName: styblope/cp/aiopsedge/cp4waiops-connector-ticket-template
    newTag: latest
