apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml
  # - topics.yaml

configurations:
  - custom-images.yaml

images:
  - name: smax
    newName: ghcr.io/styblope/cp4aiops-smax-integration
    newTag: latest
